// Code generated by rpcgen; DO NOT EDIT.
//
// Source: rpc/rpc.go
// Template: cmd/rpcgen/client.go.tmpl

package client

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/konradreiche/apigen/api"
)

func (c *Client) GetPrice(ctx context.Context, req api.GetPriceRequest) (*api.GetPriceResponse, error) {
	r, err := http.NewRequest(http.MethodGet, fmt.Sprintf("%s/%s", c.endpoint, EncodeVars(req, api.GetPriceEndpoint)), nil)
	if err != nil {
		return nil, err
	}
	resp, err := c.conn.Do(r)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		return nil, errors.New(resp.Status)
	}
	var result api.GetPriceResponse
	decoder := json.NewDecoder(resp.Body)
	err = decoder.Decode(&result)
	if err != nil {
		return nil, err
	}
	return &result, err
}
