// Code generated by rpcgen; DO NOT EDIT.
//
// Source: rpc/examples.go
// Template: cmd/rpcgen/examples.go.tmpl

package main

import (
	"encoding/json"

	"github.com/konradreiche/apigen/api"
)

var examples map[string]string = make(map[string]string)

func loadExamples() error {
	var b []byte
	var err error
	b, err = json.Marshal(api.LoginRequestExample1)
	if err != nil {
		return err
	}
	examples["LoginRequestExample1"] = string(b)
	b, err = json.Marshal(api.LoginResponseExample1)
	if err != nil {
		return err
	}
	examples["LoginResponseExample1"] = string(b)
	return nil
}
