// Code generated by rpcgen; DO NOT EDIT.
//
// Source: rpc/rpc.go
// Template: cmd/rpcgen/server.go.tmpl

package server

import (
	"context"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/konradreiche/apigen/api"
	"github.com/mitchellh/mapstructure"
)

func (s *Server) GetPriceHandleFunc(w http.ResponseWriter, r *http.Request) {
	var req api.GetPriceRequest
	params := mux.Vars(r)
	dec, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		TagName: "json",
		Result:  &req,
	})
	if err != nil {
		Encode(nil, w, nil, err)
		return
	}
	err = dec.Decode(params)
	if err != nil {
		Encode(nil, w, nil, err)
	}
	err = req.Validate()
	if err != nil {
		Encode(nil, w, nil, err)
		return
	}
	resp, err := s.api.GetPrice(context.Background(), req)
	if err != nil {
		Encode(nil, w, nil, err)
		return
	}
	Encode(nil, w, resp, nil)
}
