// Code generated by rpcgen; DO NOT EDIT.
//
// Source: api/api.go
// Template: templates/instrumentation.go.tmpl

package api

import (
	"context"
	"time"

	"github.com/DataDog/datadog-go/statsd"
	"github.com/konradreiche/apigen/metrics"
	"github.com/konradreiche/apigen/metrics/dogstatsd"
	"github.com/sirupsen/logrus"
)

type instrumentingMiddleware struct {
	requestCount   metrics.Counter
	requestLatency metrics.TimeHistogram
	errorCount     metrics.Counter
	l              *logrus.Logger
	a              API
}

// NewInstrumentingMiddleware returns a new instance of instrumentingMiddleware.
func NewInstrumentingMiddleware(a API, client *statsd.Client, log *logrus.Logger) API {
	requestCount := dogstatsd.NewCounter("request_count", 1, client, log)
	requestLatency := dogstatsd.NewTimeHistogram("request_latency", 1, client, log)
	errorCount := dogstatsd.NewCounter("error_count", 1, client, log)
	return &instrumentingMiddleware{
		requestCount:   requestCount,
		requestLatency: requestLatency,
		errorCount:     errorCount,
		l:              log,
		a:              a,
	}
}

func (im *instrumentingMiddleware) GetPrice(ctx context.Context, req GetPriceRequest) (*GetPriceResponse, error) {
	var err error
	methodTag := metrics.Tag{Key: "method", Value: "GetPrice"}
	defer func(begin time.Time) {
		if err != nil {
			errorTag := metrics.Tag{Key: "error", Value: err.Error()}
			im.errorCount.With(methodTag).With(errorTag).Add(1)
		}
		im.requestCount.With(methodTag).Add(1)
		im.requestLatency.With(methodTag).Observe(time.Since(begin))
	}(time.Now())
	response, err := im.a.GetPrice(ctx, req)
	return response, err
}
