// Code generated by apigen; DO NOT EDIT.
//
// Source: api/api.go
// Template: templates/logging.go.tmpl

package api

import (
	"context"

	"github.com/sirupsen/logrus"
)

type loggingMiddleware struct {
	log *logrus.Logger
	api API
}

func NewLoggingMiddleware(api API, log *logrus.Logger) API {
	return &loggingMiddleware{
		log: log,
		api: api,
	}
}

func (l *loggingMiddleware) Login(ctx context.Context, req LoginRequest) (*LoginResponse, error) {
	var err error
	defer func() {
		fields := logrus.Fields{
			"method":     "Login",
			"user_agent": ctx.Value("userAgent"),
		}
		if err == nil {
			l.log.WithFields(fields).Info("request")
		} else {
			fields["error"] = err
			l.log.WithFields(fields).Error("request failed")
		}
	}()
	resp, err := l.api.Login(ctx, req)
	return resp, err
}

func (l *loggingMiddleware) CreatePost(ctx context.Context, req CreatePostRequest) (*CreatePostResponse, error) {
	var err error
	defer func() {
		fields := logrus.Fields{
			"method":     "CreatePost",
			"user_agent": ctx.Value("userAgent"),
		}
		if err == nil {
			l.log.WithFields(fields).Info("request")
		} else {
			fields["error"] = err
			l.log.WithFields(fields).Error("request failed")
		}
	}()
	resp, err := l.api.CreatePost(ctx, req)
	return resp, err
}

func (l *loggingMiddleware) GetFeed(ctx context.Context, req GetFeedRequest) (*GetFeedResponse, error) {
	var err error
	defer func() {
		fields := logrus.Fields{
			"method":     "GetFeed",
			"user_agent": ctx.Value("userAgent"),
		}
		if err == nil {
			l.log.WithFields(fields).Info("request")
		} else {
			fields["error"] = err
			l.log.WithFields(fields).Error("request failed")
		}
	}()
	resp, err := l.api.GetFeed(ctx, req)
	return resp, err
}
